services:
  openfire:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    volumes:
      - openfire-data:/var/lib/openfire
    platform: linux/x86_64
volumes:
  openfire-data:
